version: '3.7'
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8081:8080"
    depends_on:
      - mongodb

  product-service:
    build: ./backend/product-service
    ports:
      - "8082:8080"
    depends_on:
      - mongodb

  order-service:
    build: ./backend/order-service
    ports:
      - "8083:8080"
    depends_on:
      - mongodb
      - kafka

  notification-service:
    build: ./backend/notification-service
    ports:
      - "8084:8080"
    depends_on:
      - kafka